### ISSUE TITLE
Add type column

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [appstract/laravel-options#25]
I suggest adding new column for `type` because developer may need to get all settings with `x` type for any use like (Building admin dashboard for changing those settings)

**Comment by teuunn** [comment]
Hi @MoatazAbdAlmageed,

First of all, thanks for your message + PR.

I get your point, but this may be different for others. Some people maybe want to use a `type_id` because they have a types tables, etc.

Also this package was supposed to be "just an easy key value storage". Feel free to fork and apply your suggested changes!

**Comment by MoatazAbdAlmageed** [comment]
Aha I got the idea.. okay keep it simple
